/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author HP
 */
public class Submarine extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form Submarine
     */
      private  MainController mainController;
    int spinnerValue; 
       int Ammo;
       int Value;
     public Submarine() {
      
    }
     
//    public Submarine() {
//        initComponents();
//    }
       public Submarine(MainController mainController) {
        this.mainController = mainController;
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblmessageSub = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSumraineMain = new javax.swing.JTextArea();
        txtSubmarine = new javax.swing.JTextField();
        btnSendSubmarine = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sldFuel = new javax.swing.JSlider();
        sldOxygen = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        btnTrident = new javax.swing.JButton();
        btnSonar = new javax.swing.JButton();
        btnThomohawk = new javax.swing.JButton();
        btnShoot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Submarine");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblmessageSub.setForeground(new java.awt.Color(255, 255, 255));
        lblmessageSub.setText("Area Not Cleared");
        getContentPane().add(lblmessageSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 9, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Soldier Count");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 9, -1, -1));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(10, null, null, 1));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 6, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ammo Count");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 34, -1, -1));

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(10, null, null, 1));
        jSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });
        getContentPane().add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 34, -1, -1));

        jCheckBox1.setBackground(new java.awt.Color(0, 92, 11));
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Position");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 103, -1, -1));

        txtSumraineMain.setColumns(20);
        txtSumraineMain.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSumraineMain.setRows(5);
        jScrollPane1.setViewportView(txtSumraineMain);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 141, 441, 113));
        getContentPane().add(txtSubmarine, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 266, 339, -1));

        btnSendSubmarine.setBackground(new java.awt.Color(255, 255, 0));
        btnSendSubmarine.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSendSubmarine.setText("Send");
        btnSendSubmarine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendSubmarineActionPerformed(evt);
            }
        });
        getContentPane().add(btnSendSubmarine, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 266, 84, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Energy");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 9, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Oxygen");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 9, -1, -1));

        sldFuel.setBackground(new java.awt.Color(0, 92, 11));
        sldFuel.setForeground(new java.awt.Color(255, 255, 255));
        sldFuel.setMajorTickSpacing(10);
        sldFuel.setOrientation(javax.swing.JSlider.VERTICAL);
        sldFuel.setPaintLabels(true);
        sldFuel.setPaintTicks(true);
        sldFuel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldFuelStateChanged(evt);
            }
        });
        getContentPane().add(sldFuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 41, -1, 213));

        sldOxygen.setBackground(new java.awt.Color(0, 92, 11));
        sldOxygen.setForeground(new java.awt.Color(255, 255, 255));
        sldOxygen.setMajorTickSpacing(10);
        sldOxygen.setOrientation(javax.swing.JSlider.VERTICAL);
        sldOxygen.setPaintLabels(true);
        sldOxygen.setPaintTicks(true);
        sldOxygen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldOxygenStateChanged(evt);
            }
        });
        getContentPane().add(sldOxygen, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 41, -1, 213));

        jPanel1.setBackground(new java.awt.Color(0, 92, 11));

        btnTrident.setBackground(new java.awt.Color(255, 255, 0));
        btnTrident.setText("Trident-2 Missile");
        btnTrident.setEnabled(false);

        btnSonar.setBackground(new java.awt.Color(255, 255, 0));
        btnSonar.setText("SonarOpearation");
        btnSonar.setEnabled(false);
        btnSonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSonarActionPerformed(evt);
            }
        });

        btnThomohawk.setBackground(new java.awt.Color(255, 255, 0));
        btnThomohawk.setText("Thomohawk MIissile");
        btnThomohawk.setEnabled(false);

        btnShoot.setBackground(new java.awt.Color(255, 255, 0));
        btnShoot.setText("Shoot");
        btnShoot.setEnabled(false);
        btnShoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShootActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnThomohawk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSonar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTrident, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSonar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShoot, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTrident, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThomohawk, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(188, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSonarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSonarActionPerformed

    private void btnSendSubmarineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendSubmarineActionPerformed
        // TODO add your handling code here:
         String privateMessage = txtSubmarine.getText();
             mainController.SendPriavteMessage("Submarine:"+privateMessage);
    }//GEN-LAST:event_btnSendSubmarineActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        
          
        
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void sldFuelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldFuelStateChanged
        // TODO add your handling code here:
        Value=(int)sldFuel.getValue();
  
    }//GEN-LAST:event_sldFuelStateChanged

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        spinnerValue = (int) jSpinner1.getValue();
        if (spinnerValue==0){
        mainController.DieWarning("Submarime:Our All Soldiers Died Sorry Boss... ");
        
        }
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jSpinner2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner2StateChanged
        // TODO add your handling code here:
        Ammo = (int) jSpinner2.getValue();
    }//GEN-LAST:event_jSpinner2StateChanged

    private void btnShootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShootActionPerformed
        // TODO add your handling code here:
        int ammoCount=(int)jSpinner2.getValue();
        if(ammoCount>0){
            ammoCount--;
            jSpinner2.setValue(ammoCount);
                } 
        if(ammoCount==0){
            mainController.Warning("Submarine:Ammo Count is 0 \n Please  Help me!!!!");
        
        }
    }//GEN-LAST:event_btnShootActionPerformed

    private void sldOxygenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldOxygenStateChanged
        // TODO add your handling code here:
        int Oxygen=sldOxygen.getValue();
        if(Oxygen<= 20){
            mainController.OxygenLevelWarning("Oxygen Level is Running Low...");
        
        } if(Oxygen== 0){
            mainController.OxygenLevelWarning("Our Oxygen is Over!!! Good Bye World ");
        
        }  
        
    }//GEN-LAST:event_sldOxygenStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Submarine().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendSubmarine;
    private javax.swing.JButton btnShoot;
    private javax.swing.JButton btnSonar;
    private javax.swing.JButton btnThomohawk;
    private javax.swing.JButton btnTrident;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JLabel lblmessageSub;
    private javax.swing.JSlider sldFuel;
    private javax.swing.JSlider sldOxygen;
    private javax.swing.JTextField txtSubmarine;
    private javax.swing.JTextArea txtSumraineMain;
    // End of variables declaration//GEN-END:variables
 public int[] getDetails(){
        
        int[] ar = {spinnerValue,Ammo, Value};
        return ar;
       
} 
    
    
      @Override
     public void SendMessagePrivatelyFromMain(String MainSelected, boolean MainStatus, String privateMessage){
       if ( MainStatus == true && MainSelected.equals("Submarine")  ) {
             txtSumraineMain.append("\n Private Message:"+privateMessage);
          
        } else if(MainStatus==false){
         txtSumraineMain.append(privateMessage+"\n"); 
         System.out.println("hi");
       }
     
     
     }  
   
     @Override
    public void updateArea(boolean status){
		  if (status == true) {
             lblmessageSub.setText("Area Cleared");
          
        } else if (status == false) {
            lblmessageSub.setText("Area Not Cleared");
        }
	}
    
    /* @Override
     public void SendMainmessge(String message){
          SumraineMainTextArea.setText(message); 
           System.out.println("hi");
    
    }*/
      @Override
 public void btnEnable(int Value){
     boolean select = jCheckBox1.isSelected();
     if (select== true) {
         if(Value>25){
           btnShoot.setEnabled(true);
     }else{
          btnShoot.setEnabled(false);
     }
         if(Value>50){
           btnSonar.setEnabled(true);
     }else{
          btnSonar.setEnabled(false);
     }
       if(Value>75){
          btnThomohawk.setEnabled(true);
     }else{
         btnThomohawk.setEnabled(false);
     }   
       if(Value>85){
          btnTrident.setEnabled(true);
     }else{
         btnTrident.setEnabled(false);
     }   
       
       
       
     }
     
 
 }

}
