/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

/**
 *
 * @author HP
 */
public class Tank extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form Tank
     */
    int spinnerValue; 
       int Ammo;
       int Value;
     private  MainController mainController;
     public Tank() {
      
    }

     public Tank(MainController mainController) {
        this.mainController = mainController;
        initComponents();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AreaClearTank = new javax.swing.JLabel();
        ShootbtnTank = new javax.swing.JButton();
        MissileBtn = new javax.swing.JButton();
        RedarBtn = new javax.swing.JButton();
        RotateBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        TankTextMainArea = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        SendTankBtn = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tank");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AreaClearTank.setForeground(new java.awt.Color(255, 255, 255));
        AreaClearTank.setText("Area Not Cleared");
        getContentPane().add(AreaClearTank, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 0, -1, -1));

        ShootbtnTank.setBackground(new java.awt.Color(255, 255, 0));
        ShootbtnTank.setText("Shoot");
        ShootbtnTank.setEnabled(false);
        getContentPane().add(ShootbtnTank, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 43, 116, 31));

        MissileBtn.setBackground(new java.awt.Color(255, 255, 0));
        MissileBtn.setText("Missile Operation");
        MissileBtn.setEnabled(false);
        MissileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MissileBtnActionPerformed(evt);
            }
        });
        getContentPane().add(MissileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 43, -1, 31));

        RedarBtn.setBackground(new java.awt.Color(255, 255, 0));
        RedarBtn.setText("Redar Operation");
        RedarBtn.setEnabled(false);
        getContentPane().add(RedarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 86, -1, 32));

        RotateBtn.setBackground(new java.awt.Color(255, 255, 0));
        RotateBtn.setText("Rotate Shooting");
        RotateBtn.setEnabled(false);
        getContentPane().add(RotateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 86, 122, 32));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Soldier Count");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 18, -1, -1));

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 15, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ammo Count");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 46, -1, -1));

        jSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });
        getContentPane().add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 43, -1, -1));

        jCheckBox1.setBackground(new java.awt.Color(0, 92, 11));
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Position");
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 98, -1, -1));

        TankTextMainArea.setColumns(20);
        TankTextMainArea.setRows(5);
        jScrollPane1.setViewportView(TankTextMainArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 149, 423, 99));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 266, 325, -1));

        SendTankBtn.setBackground(new java.awt.Color(255, 255, 0));
        SendTankBtn.setText("Send");
        SendTankBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendTankBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SendTankBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 266, 84, -1));

        jSlider1.setBackground(new java.awt.Color(0, 92, 11));
        jSlider1.setForeground(new java.awt.Color(255, 255, 255));
        jSlider1.setMajorTickSpacing(10);
        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        getContentPane().add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 6, -1, 282));

        jPanel1.setBackground(new java.awt.Color(0, 92, 11));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SendTankBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendTankBtnActionPerformed
        // TODO add your handling code here:
        String privateMessage = jTextField1.getText();
             mainController.SendPriavteMessage("Tank:"+privateMessage);
    }//GEN-LAST:event_SendTankBtnActionPerformed

    private void MissileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MissileBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MissileBtnActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        spinnerValue = (int) jSpinner1.getValue();
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jSpinner2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner2StateChanged
        // TODO add your handling code here:
        Ammo = (int) jSpinner2.getValue();
    }//GEN-LAST:event_jSpinner2StateChanged

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        Value=(int)jSlider1.getValue();
    }//GEN-LAST:event_jSlider1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Tank().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AreaClearTank;
    private javax.swing.JButton MissileBtn;
    private javax.swing.JButton RedarBtn;
    private javax.swing.JButton RotateBtn;
    private javax.swing.JButton SendTankBtn;
    private javax.swing.JButton ShootbtnTank;
    private javax.swing.JTextArea TankTextMainArea;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

     public int[] getDetails(){
        
        int[] ar = {spinnerValue,Ammo, Value};
        return ar;
       
} 
    @Override
     public void SendMessagePrivatelyFromMain(String MainSelected, boolean MainStatus, String privateMessage){
       System.out.println(MainSelected);
         if ( MainStatus == true && MainSelected =="Tank"  ) {
           TankTextMainArea.append("\n Private Message:"+privateMessage);
         
        } else if(MainStatus==false){
        TankTextMainArea.append(privateMessage+"\n"); 
           System.out.println("hi");
       } 
     
     }  

    @Override
    public void updateArea(boolean status){
		  if (status == true) {
              AreaClearTank.setText(" Area Cleared");
          
        } else if (status == false) {
            AreaClearTank.setText("Area Not Cleared");
        }
	}
    
   /*  @Override
    public void SendMainmessge(String message){
           TankTextMainArea.setText(message); 
           System.out.println("hi");
    
    }*/
     @Override
 public void btnEnable(int Value){
     boolean select = jCheckBox1.isSelected();
     if (select== true) {
         if(Value>25){
         ShootbtnTank.setEnabled(true);
     }else{
          ShootbtnTank.setEnabled(false);
     }
      if(Value>50){
         MissileBtn.setEnabled(true);
     }else{
          MissileBtn.setEnabled(false);
     }   
         if(Value>75){
        RedarBtn.setEnabled(true);
     }else{
         RedarBtn.setEnabled(false);
     }   
           if(Value>85){
       RotateBtn.setEnabled(true);
     }else{
        RotateBtn.setEnabled(false);
     }   
     }
     
 }
    
}
